apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config-qnap
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: qnap-nfs
  resources:
    requests:
      storage: 10Gi
