apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-nfs-pv
spec:
  capacity:
    storage: 400Gi
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  nfs:
    server: 192.168.1.82
    path: /mnt/nextcloud-data
  persistentVolumeReclaimPolicy: Retain
