apiVersion: v1
kind: ServiceAccount
metadata:
  name: freshrss-sa
  labels:
    {{- include "freshrss.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: freshrss-secret-reader
  labels:
    {{- include "freshrss.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["freshrss-db-credentials"]
  verbs: ["get", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  resourceNames: ["freshrss"]
  verbs: ["patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: freshrss-secret-reader-binding
  labels:
    {{- include "freshrss.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: freshrss-sa
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: freshrss-secret-reader
  apiGroup: rbac.authorization.k8s.io 