apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "audiobookshelf.fullname" . }}
  labels:
    {{- include "audiobookshelf.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "audiobookshelf.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "audiobookshelf.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            {{- if .Values.persistence.config.enabled }}
            - name: config
              mountPath: /config
            {{- end }}
            {{- if .Values.persistence.metadata.enabled }}
            - name: metadata
              mountPath: /metadata
            {{- end }}
            {{- if .Values.persistence.audiobooks.enabled }}
            - name: audiobooks
              mountPath: /audiobooks
            {{- end }}
      volumes:
        {{- if .Values.persistence.config.enabled }}
        - name: config
          persistentVolumeClaim:
            claimName: {{ include "audiobookshelf.fullname" . }}-config
        {{- end }}
        {{- if .Values.persistence.metadata.enabled }}
        - name: metadata
          persistentVolumeClaim:
            claimName: {{ include "audiobookshelf.fullname" . }}-metadata
        {{- end }}
        {{- if .Values.persistence.audiobooks.enabled }}
        - name: audiobooks
          persistentVolumeClaim:
            claimName: {{ include "audiobookshelf.fullname" . }}-audiobooks
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
