{
 "title": "Nextcloud",
 "tags": [ "self-hosted" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Nextcloud!", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Running pods (nextcloud)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "SUM(up{namespace=\"nextcloud\", pod!~\"nextcloud-imaginary.*\", pod!~\"nextcloud-cron.*\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Status codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(response_total{namespace=\"nextcloud\", status_code=~\"2..\", pod=~\"nextcloud-imaginary.*\"}[$__rate_interval]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(response_total{namespace=\"nextcloud\", status_code=~\"3..\", pod=~\"nextcloud-imaginary.*\"}[$__rate_interval]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(rate(response_total{namespace=\"nextcloud\", status_code=~\"4..\", pod=~\"nextcloud-imaginary.*\"}[$__rate_interval]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(response_total{namespace=\"nextcloud\", status_code=~\"5..\", pod=~\"nextcloud-imaginary.*\"}[$__rate_interval]))",
     "legendFormat": "5xx"
    }
   ]
  },
  { "title": "Imaginary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Running pods (imaginary)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "SUM(up{namespace=\"nextcloud\", pod=~\"nextcloud-imaginary.*\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Status codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(response_total{namespace=\"nextcloud\", status_code=~\"2..\", pod!~\"nextcloud-imaginary.*\", pod!~\"nextcloud-cron.*\"}[$__rate_interval]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(response_total{namespace=\"$nextcloud\", status_code=~\"5..\", pod!~\"nextcloud-imaginary.*\", pod!~\"nextcloud-cron.*\"}[$__rate_interval]))",
     "legendFormat": "5xx"
    },
    {
     "expr": "sum(rate(response_total{namespace=\"$nextcloud\", status_code=~\"3..\", pod!~\"nextcloud-imaginary.*\", pod!~\"nextcloud-cron.*\"}[$__rate_interval]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(rate(response_total{namespace=\"$nextcloud\", status_code=~\"4..\", pod!~\"nextcloud-imaginary.*\", pod!~\"nextcloud-cron.*\"}[$__rate_interval]))",
     "legendFormat": "4xx"
    }
   ]
  }
 ]
}