replicaCount: 1

image:
  repository: deluan/navidrome
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 4533

ingress:
  enabled: false
  className: nginx
  annotations: {}
  hosts: []
  tls: []

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  storageClass: qnap-nfs
  size: 10Gi
  musicSize: 50Gi

config:
  ND_LOGLEVEL: info
  ND_PORT: "4533"
  ND_BASEURL: ""
  ND_SESSIONTIMEOUT: "720h"
  ND_ENABLETRANSCODINGCONFIG: "false"

oidc:
  enabled: false
  providerMetadataUrl: ""
  clientId: ""
  secretName: ""
  secretKey: clientSecret
