apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sentinel-sre.fullname" . }}-env
  labels:
    {{- include "sentinel-sre.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if not .Values.anthropic.existingSecret }}
  ANTHROPIC_API_KEY: {{ .Values.anthropic.apiKey | quote }}
  {{- end }}
  SECRET_KEY: {{ .Values.secretKey | quote }}
  {{- if not .Values.database.existingSecret }}
  DATABASE_URL: {{ include "sentinel-sre.databaseURL" . | quote }}
  {{- end }}
  {{- if .Values.postgresql.enabled }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.password | quote }}
  {{- end }}
