apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "darek.fullname" . }}-config
  labels:
    {{- include "darek.labels" . | nindent 4 }}
data:
  config.yaml: |-
    {{- .Values.config | nindent 4 }}
