{{- if .Values.migrations.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "darek.fullname" . }}-migrate
  labels:
    {{- include "darek.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 3
  ttlSecondsAfterFinished: 600
  template:
    metadata:
      labels:
        {{- include "darek.selectorLabels" . | nindent 8 }}
        job: migrate
    spec:
      restartPolicy: Never
      serviceAccountName: {{ include "darek.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: migrate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["migrate"]
          envFrom:
            - secretRef:
                name: {{ include "darek.fullname" . }}-env
          env:
            - name: HOME
              value: /home/nonroot
          volumeMounts:
            - name: config
              mountPath: /home/nonroot/.darek/config.yaml
              subPath: config.yaml
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: {{ include "darek.fullname" . }}-config
{{- end }}
