{{- if .Values.envSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "darek.fullname" . }}-env
  labels:
    {{- include "darek.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.secrets }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
